/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Funcionalidades;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author 57322
 */
public class GUI extends javax.swing.JFrame {

    /*Ruta por defecto*/
    private String archivo = "registros.txt";
    /*Ruta por defecto*/
    private String copiaArchivo = "copiaArchivo.txt";
    /*Objeto de las funcionalidades*/
    Funcionalidades F = new Funcionalidades();

    /*Getters and Setters*/
    public String getArchivo() {
        return archivo;
    }

    public String getCopiaArchivo() {
        return copiaArchivo;
    }

    public void setCopiaArchivo(String copiaArchivo) {
        this.copiaArchivo = copiaArchivo;
    }

    public void setArchivo(String archivo) {
        this.archivo = archivo;
    }

    /**
     * Creates new form Principal
     */
    public GUI() {
        initComponents();
        if (F.validarArchivo(archivo)) {
            F.crearArbol(archivo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jCheckBoxMenuItem5 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem6 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        panel2 = new java.awt.Panel();
        jLabel3 = new javax.swing.JLabel();
        newClave = new javax.swing.JTextField();
        panel1 = new java.awt.Panel();
        jLabel6 = new javax.swing.JLabel();
        newDato = new javax.swing.JTextField();
        btnNIndex = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCIndex = new javax.swing.JTextField();
        txtCNIndex = new javax.swing.JTextField();
        jButtonAgregarRegistro = new javax.swing.JButton();
        btnIndex = new javax.swing.JButton();
        txtNum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rIndex = new javax.swing.JLabel();
        r_Index = new javax.swing.JLabel();
        r_nindex = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        r_Index1 = new javax.swing.JLabel();
        r_Index2 = new javax.swing.JLabel();
        t_index = new javax.swing.JLabel();
        t_nindex = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnLIMPIAR = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("jCheckBoxMenuItem4");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jCheckBoxMenuItem5.setSelected(true);
        jCheckBoxMenuItem5.setText("jCheckBoxMenuItem5");

        jCheckBoxMenuItem6.setSelected(true);
        jCheckBoxMenuItem6.setText("jCheckBoxMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        panel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AGREGAR REGISTRO:");
        jLabel3.setDoubleBuffered(true);

        newClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newClaveActionPerformed(evt);
            }
        });

        panel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel6.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("INDEXACIÓN BD2");
        jLabel6.setDoubleBuffered(true);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnNIndex.setBackground(new java.awt.Color(0, 0, 0));
        btnNIndex.setForeground(new java.awt.Color(255, 255, 255));
        btnNIndex.setText("BUSCAR NO INDEXADA");
        btnNIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNIndexActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GENERAR ARCHIVO");
        jLabel4.setDoubleBuffered(true);

        btnGenerar.setBackground(new java.awt.Color(0, 0, 0));
        btnGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerar.setText("GENERAR");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BUSQUEDA INDEXADA:");
        jLabel7.setDoubleBuffered(true);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("BUSQUEDA NO INDEXADA:");
        jLabel9.setDoubleBuffered(true);

        txtCIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCIndexActionPerformed(evt);
            }
        });

        jButtonAgregarRegistro.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAgregarRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregarRegistro.setText("AGREGAR REGISTRO");
        jButtonAgregarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarRegistroActionPerformed(evt);
            }
        });

        btnIndex.setBackground(new java.awt.Color(0, 0, 0));
        btnIndex.setForeground(new java.awt.Color(255, 255, 255));
        btnIndex.setText("BUSCAR INDEXADA");
        btnIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndexActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("N° REGISTROS");

        rIndex.setFont(new java.awt.Font("DialogInput", 2, 14)); // NOI18N

        r_Index.setForeground(new java.awt.Color(255, 255, 255));
        r_Index.setText("______");

        r_nindex.setForeground(new java.awt.Color(255, 255, 255));
        r_nindex.setText("______");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TIEMPOS DE EJECUCIÓN:");
        jLabel10.setDoubleBuffered(true);

        r_Index1.setForeground(new java.awt.Color(255, 255, 255));
        r_Index1.setText("INDEXADA:");

        r_Index2.setForeground(new java.awt.Color(255, 255, 255));
        r_Index2.setText("NO INDEXADA:");

        t_index.setForeground(new java.awt.Color(255, 255, 255));
        t_index.setText("______");

        t_nindex.setForeground(new java.awt.Color(255, 255, 255));
        t_nindex.setText("______");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CLAVE");
        jLabel5.setDoubleBuffered(true);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DATO");
        jLabel8.setDoubleBuffered(true);

        btnLIMPIAR.setBackground(new java.awt.Color(0, 0, 0));
        btnLIMPIAR.setForeground(new java.awt.Color(255, 255, 255));
        btnLIMPIAR.setText("LIMPIAR");
        btnLIMPIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLIMPIARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)))
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCIndex, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(txtCNIndex))
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel2Layout.createSequentialGroup()
                                        .addGap(173, 173, 173)
                                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(r_nindex)
                                            .addComponent(r_Index)))
                                    .addComponent(btnNIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)))))
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGenerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLIMPIAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62))
            .addComponent(jSeparator1)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel5))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addComponent(newClave, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(newDato, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAgregarRegistro))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(70, 70, 70))
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(r_Index1)
                .addGap(18, 18, 18)
                .addComponent(t_index, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(r_Index2)
                .addGap(18, 18, 18)
                .addComponent(t_nindex, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
            .addComponent(jSeparator3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGenerar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(rIndex)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIndex)
                            .addComponent(r_Index))
                        .addGap(18, 18, 18)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCNIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNIndex)
                            .addComponent(r_nindex))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnLIMPIAR)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r_Index1)
                    .addComponent(t_index)
                    .addComponent(r_Index2)
                    .addComponent(t_nindex))
                .addGap(19, 19, 19)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(newClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregarRegistro))
                .addGap(52, 52, 52))
        );

        r_Index.getAccessibleContext().setAccessibleName("_______");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newClaveActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // BOTÓN GENERAR ARCHIVO
        if (generarArchivo()) {

            JOptionPane.showMessageDialog(this, "ARCHIVO GENERADO");

        } else {

            showMessageDialog(null, "ARCHIVO NO GENERADO", "GENERAR ARCHIVO", ERROR_MESSAGE);
        }
        this.txtNum.setText("");
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndexActionPerformed
        // TODO add your handling code here:

        //Busqueda indexada
        if (!existeArchivo()) {
            showMessageDialog(null, "DEBES GENERAR EL ARCHIVO", "GENERAR ARCHIVO", ERROR_MESSAGE);

        } else if (campoVacio(this.txtCIndex.getText())) {
            showMessageDialog(null, "CAMPO VACIO ", "BUSQUEDA", ERROR_MESSAGE);
        } else {
            //Se mide el tiempo de ejecución
            long startTime = System.nanoTime();
            String r = busquedaIndexada();
            long endTime = System.nanoTime() - startTime; // tiempo en que se ejecuta su método
            if (r.equals("No")) {
                showMessageDialog(null, "NO SE ENCONTRÓ CLAVE EN EL ARCHIVO", "ARCHIVO", ERROR_MESSAGE);
            } else {

                this.r_Index.setText(r);
                //this.t_index.setText(String.valueOf(endTime));
            }
            this.t_index.setText(String.valueOf(endTime));
        }
    }//GEN-LAST:event_btnIndexActionPerformed

    private void btnNIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNIndexActionPerformed
        // TODO add your handling code here:
        //Busqueda NO Indexada
        if (!existeArchivo()) {
            showMessageDialog(null, "DEBES GENERAR EL ARCHIVO", "GENERAR ARCHIVO", ERROR_MESSAGE);

        } else if (campoVacio(this.txtCNIndex.getText())) {
            showMessageDialog(null, "CAMPO VACIO ", "BUSQUEDA", ERROR_MESSAGE);
        } else {
            //Se mide el tiempo de ejecución
            long startTime = System.nanoTime();

            String r = busquedaNoIndexada();

            long endTime = System.nanoTime() - startTime; // tiempo en que se ejecuta su método
            if (r.equals("No")) {
                showMessageDialog(null, "NO SE ENCONTRÓ CLAVE EN EL ARCHIVO", "ARCHIVO", ERROR_MESSAGE);
            } else {

                this.r_nindex.setText(r);
                //this.t_nindex.setText(String.valueOf(endTime));
            }
            this.t_nindex.setText(String.valueOf(endTime));
        }
    }//GEN-LAST:event_btnNIndexActionPerformed

    private void jButtonAgregarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarRegistroActionPerformed
        // TODO add your handling code here:
        //Insertar nuevo registro en el archivo

        if (!existeArchivo()) {
            showMessageDialog(null, "DEBES GENERAR EL ARCHIVO", "GENERAR ARCHIVO", ERROR_MESSAGE);
        } else if (campoVacio(this.newClave.getText()) == false && campoVacio(this.newDato.getText()) == false) {
           
            /*Validar rango de los regisros {clave:valor}*/
            int key = Integer.parseInt(this.newClave.getText());
            int valor = Integer.parseInt(this.newDato.getText());

            if (key <= 1000000 && key >= 0 && valor <= 1000000 && valor >= 0) {
                if (F.agregarNuevoElemento(this.getArchivo(), this.getCopiaArchivo(), this.newClave.getText(), this.newDato.getText())) {
                    showMessageDialog(null, "DATO AGREGADO EXITOSAMENTE ");
                } else {
                    showMessageDialog(null, "CLAVE EXISTENTE", "ERORR", ERROR_MESSAGE);
                }
            } else {
                showMessageDialog(null, "FUERA DE RANGO", "ERORR", ERROR_MESSAGE);
            }

            this.newClave.setText("");
            this.newDato.setText("");
        } else {
            showMessageDialog(null, "CAMPO VACIO ", "NO SE GENERÓ REGISTRO", ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonAgregarRegistroActionPerformed

    private void txtCIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCIndexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCIndexActionPerformed

    private void btnLIMPIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLIMPIARActionPerformed
        this.txtCIndex.setText("");
        this.txtCNIndex.setText("");
        this.t_index.setText("");
        this.t_nindex.setText("");
        this.r_Index.setText("");
        this.r_nindex.setText("");

    }//GEN-LAST:event_btnLIMPIARActionPerformed

    /*Genera un nuevo archivo (si ya existe lo sobre-escribe)*/
    public boolean generarArchivo() {

        if (this.txtNum.getText().equals("")) {
            showMessageDialog(null, "REVISE LA INFORMACIÓN", "GENERAR ARCHIVO", ERROR_MESSAGE);
        } else {
            int numReg = Integer.parseInt(this.txtNum.getText());
            boolean flag = F.generarArchivo(this.getArchivo(), numReg);
            return flag;
        }

        return false;

    }

    /*Busqueda indexada*/
    public String busquedaIndexada() {

        String clave = this.txtCIndex.getText();
        return F.busquedaIndexada(clave, "copiaArchivo.txt");
    }

    /*Busqueda NO indexada*/
    public String busquedaNoIndexada() {
        String clave = this.txtCNIndex.getText();
        return F.busquedaNoindexada(clave, archivo);
    }

    public boolean existeArchivo() {
        return F.validarArchivo(archivo);

    }

    public boolean campoVacio(String campo) {
        if (campo.equals("")) {
            return true; //el campo esta vacio
        } else {
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnIndex;
    private javax.swing.JButton btnLIMPIAR;
    private javax.swing.JButton btnNIndex;
    private javax.swing.JButton jButtonAgregarRegistro;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField newClave;
    private javax.swing.JTextField newDato;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private javax.swing.JLabel rIndex;
    private javax.swing.JLabel r_Index;
    private javax.swing.JLabel r_Index1;
    private javax.swing.JLabel r_Index2;
    private javax.swing.JLabel r_nindex;
    private javax.swing.JLabel t_index;
    private javax.swing.JLabel t_nindex;
    private javax.swing.JTextField txtCIndex;
    private javax.swing.JTextField txtCNIndex;
    private javax.swing.JTextField txtNum;
    // End of variables declaration//GEN-END:variables
}
